---
- name: "TEST: Xdebug needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ xdebug_extension_path }}"
    - "{{ xdebug_archive_path }}"
  register: xdebug_install
  failed_when: xdebug_install.stat.exists == false

- name: "TEST: Xdebug should be configured in php.ini"
  shell: grep -o "{{ xdebug_extension_name }}" {{ php_ini }} || echo "absent"
  register: xdebug_phpini
  changed_when: xdebug_phpini == "absent"
  failed_when: xdebug_phpini == "absent"

- name: "TEST: Xdebug should use the latest release"
  shell: php -c {{ php_ini }} -i | grep -m1 -o {{ xdebug_stable_release }} || "absent"
  register: xdebug_phpini_version
  changed_when: xdebug_phpini_version == "absent"
  failed_when: xdebug_phpini_version == "absent"
