---
- name: "TEST: System needs to be cleaned up"
  shell: dpkg -l | grep vim-tiny || echo "absent"
  register: system_cleanup
  changed_when: system_cleanup.stdout != 'absent'
  failed_when: system_cleanup.stdout != 'absent'

- name: "TEST: System files need to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ bash_aliases }}"
    - "{{ vimrc }}"
    - "{{ vim_dir }}"
  register: system
  failed_when: system.stat.exists == false

- name: "TEST: sources.list file needs to be correctly configured"
  shell: grep -o "{{ codename }} main contrib non-free" || echo "absent"
  register: sources_list_repos
  changed_when: sources_list_repos.stdout != 'absent'
  failed_when: sources_list_repos.stdout != 'absent'

- name: "TEST: System packages need to be correctly installed"
  shell: dpkg -l | grep {{ item }}
  with_items:
    - ack-grep
    - apt-transport-https
    - curl
    - dstat
    - exuberant-ctags
    - git
    - htop
    - iputils-ping
    - libfontconfig1
    - logrotate
    - lsof
    - ncdu
    - netcat
    - net-tools
    - ntp
    - patchutils
    - strace
    - sysstat
    - telnet
    - tcpdump
    - time
    - vim-gtk
    - wget
    - xterm
  register: system_packages
  changed_when: system_packages == ''
