---
- include: apache-common-tests.yml

- name: "TEST: Check if Apache and web tools are installed"
  shell: dpkg -l | grep {{ item }}
  with_items:
    - apache2
    - apache2-utils
    - goaccess
  register: apache_packages
  changed_when: apache_packages == ''

- name: "TEST: APACHE_RUN_USER should be set"
  shell: grep -o "export APACHE_RUN_USER={{ user }}" {{ apache_envvars }} || echo "absent"
  register: apache_run_user
  changed_when: apache_run_user.stdout == "absent"
  failed_when: apache_run_user.stdout == "absent"

- name: "TEST: Web server group should be added to the drucker user"
  shell: groups {{ user }} | awk '{print $NF}'
  register: group_check
  changed_when: group_check.stdout != apache_user
  failed_when: group_check.stdout != apache_user

- name: "TEST: Permissions should be correct in the webroot"
  shell: stat -c %U:%G "{{ item }}" | grep "{{ user }}:{{ apache_user }}" || echo "Wrong permissions"
  with_items:
    - "{{ drucker_site }}"
    - "{{ adminer_root }}"
    - "{{ phpmyadmin_root }}"
    - "{{ import_dir }}"
  register: webroot_permissions
  changed_when: webroot_permissions.stdout == "Wrong permissions"
  failed_when: webroot_permissions.stdout == "Wrong permissions"

- name: "TEST: All URLs should be accessible"
  uri:
    url: "{{ item }}"
  with_items:
    - http://{{ user }}.{{ tld }}
    - http://search.{{ tld }}:{{ solr_port }}/solr/#
    - http://phpmyadmin.{{ tld }}
    - http://adminer.{{ tld }}
