---
- name: "TEST: Drupal needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ drupal_root }}"
    - "{{ drupal_root }}/{{ default_configuration_dir }}"
    - "{{ drupal_docroot }}"
    - "{{ files_dir }}"
    - "{{ libraries_dir }}"
    - "{{ settings_php }}"
    - "{{ services_yml }}"
    - "{{ simpletest_dir }}"
    - "{{ drupal_git }}"
    - "{{ drupal_gitignore }}"
    - "{{ db_data }}/{{ user }}"
    - "{{ phpunit_xml }}"
    - "{{ import_dir }}"
    - "{{ archives_dir }}"
    - "{{ log_dir }}/{{ user }}-access.log"
    - "{{ log_dir }}/{{ user }}-error.log"
  register: drupal
  failed_when: drupal.stat.exists == false

- name: "TEST: settings.php should hold the correct trusted_host_patterns setting"
  shell: grep -F "{{ user }}\.{{ tld }}" {{ settings_php }} || echo "missing"
  register: trusted_host_patterns
  changed_when: trusted_host_patterns.stdout == "missing"
  failed_when: trusted_host_patterns.stdout == "missing"

- set_fact:
    expected_ownership: "{{ user }}:{{ apache_user }}"

- name: "TEST: The styles directory should have correct ownership"
  shell: stat -c %U:%G {{ files_dir }}/styles
  register: styles_dir_ownership
  changed_when: styles_dir_ownership.stdout != expected_ownership
  failed_when: styles_dir_ownership.stdout != expected_ownership

- name: "TEST: Make sure the codebase was added under version control"
  shell: git -C {{ drupal_root }} log --oneline | grep -o "Initial commit" || echo 'no commit'
  args:
    warn: no
  register: initial_commit
  changed_when: initial_commit == "no commit"
  failed_when: initial_commit == "no commit"

- name: "TEST: Ensure remote MySQL databases can be managed"
  shell: dpkg -l | grep "python-mysqldb"
  register: remote_db_management
  changed_when: remote_db_management == ''

- name: "TEST: Ensure Drupal can talk to the Solr backend"
  shell: grep -o "{{ search_ip }}" {{ hosts_file }} || echo "absent"
  register: search_hostname_check
  changed_when: search_hostname_check == "absent"
  failed_when: search_hostname_check == "absent"
